name: main

on: [push, pull_request]
# Replace with your branch name if necessary

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'

    - name: Build package for Release
      run: dotnet pack -c Release

    - name: Upload NuGet package to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        files: '**/AspNetCore.Proxy.*.nupkg'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
